### PR TITLE
A approach about the Chinese texts wrapping lines

### PR DESCRIPTION
**Pull request by Crapsky233**
I found a simple and useful way to make the Chinese and English texts warps at the same time. Hope this may help you.

### CODE REVIEW

**Comment by JavidPack** [comment]
This might work. I'm worried about punctuation ending up at the start of a new line, but if this works well enough I'll just keep it.

Have you been testing your changes in-game with a clone of this mod?

**Comment by Crapsky233** [comment]
Sure. And if English punctuation doesn't have a space before it. It won't appears at the start of a new line.

**Comment by Crapsky233** [comment]
@JavidPack Here are some screenshots.
English
Chinese

**Comment by JavidPack** [comment]
Seems to work great. Thanks.

**Pull request merged**
